# Generated by Django 3.1.5 on 2021-01-18 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repo_app', '0003_auto_20210118_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='repo',
        ),
        migrations.AddField(
            model_name='image',
            name='author',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='upload',
            field=models.ImageField(blank='True', null=True, upload_to=''),
        ),
    ]
